name: GodSpeed
favicon: null
layout_spectrum: 0
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030d0f'
    - '#fbdac7'
    - '#283637'
    - '#e4a187'
    - '#b74e4b'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
