name: GodSpeed
favicon: null
layout_spectrum: 0.662437908584252
typography_spectrum: 0.7113012778572738
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7130345413461328
  lightness: 0.08969196816906333
  saturation: 0.32782234577462077
  rhythmicContrast: 0.6161080372985452
purpose: []
